version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/

artifacts:
  files:
    - '**/*'
  base-directory: base_location
  name: dev-backend-build-artifact
  discard-paths: no

hooks:
  BeforeInstall:
    - location: bash/before_deployment.sh
  AfterInstall:
    - location: bash/after_deployment.sh
      timeout: 180
  ApplicationStart:
    - location: bash/functional_test.sh
      timeout: 3600
  ValidateService:
    - location: bash/monitor.sh
      timeout: 3600
